name: "ClickUp Task Updater"
description: "Extract ClickUp ID from PR title and update task status"
author: "William Lin"
branding:
  icon: "check-circle"
  color: "blue"

inputs:
  github_token:
    description: "GitHub Token"
    required: true
  clickup_api_key:
    description: "ClickUp API Key"
    required: true
  new_clickup_status:
    description: "New status for the ClickUp task"
    required: true
  should_update_pr_description:
    description: "Whether to update the PR description"
    required: false
    default: "false"
  should_add_task_comment:
    description: "Whether to add a comment to the ClickUp task with the PR link"
    required: false
    default: "false"

runs:
  using: "node16"
  main: "dist/index.js"
